- name : PLAY1
  hosts : local
  connection : local # managing its own node. No need of credentials (ssh username and ssh password)
  tasks :
  - name : PLAY1 and TASK1
    ansible.builtin.debug:
      msg : "Hello from play1 and task1"

- name : PLAY2
  hosts : local
  connection : local # managing its own node. No need of credentials (ssh username and ssh password)
  tasks :
  - name : PLAY2 and TASK2
    ansible.builtin.debug:
      msg : "Hello from play2 and task2"