- name : variables
  hosts : local
  connection : local
  vars : # PLAY level Variables, global variables
    COURSE : "DevOps with AWS"
    DURATION : 120HRS
    TRAINER : Sivakumar
  tasks :
    - name : print the task1 variables
      vars :  # TASK level Variables. Accessible only in the task. Task variables/local variables override Play / global variables
        COURSE : Ansible
        DURATION : 10HRS
      ansible.builtin.debug:
       msg : "Course is {{COURSE}}. Duration is {{DURATION}}. Trainer is {{ TRAINER}}"
    
    - name : print the task2 variables
      ansible.builtin.debug:
       msg : "Course is {{COURSE}}. Duration is {{DURATION}}. Trainer is {{ TRAINER}}"
  