- name : print variables from prompt
  hosts : local
  connection : local
  vars_prompt : # variables from prompt
    - name : COURSE
      prompt : Please enter the course name
      private : false
    - name : DURATION
      prompt : Please enter duration
      private : false
    - name : TRAINER
      prompt : Please entertrainer name
      private : false
  tasks :
  - name : print course information through prompt
    ansible.builtin.debug:
      msg :  "Course is {{COURSE}}. Duration is {{DURATION}}. Trainer is {{ TRAINER}}"