- name : Print variables from arguments
  hosts : web
  tasks :
  - name : task1 - Vars from arguments
    ansible.builtin.debug :
      msg : "Course is {{ COURSE}}. Duration is {{ DURATION}}. Speaker is {{ SPEAKER }}"