- name : "Variables preferences"
  hosts : local
  connection : local
  # vars :
  #   GREET : "PLAY"
  # vars_files :
  # - vars.yaml
  # vars_prompt :
  # - name : GREET
  #   prompt : enter the value
  #   private : false
  tasks :
  - name : "task 1 - Variables preferences"
    # vars : 
    #   GREET : "TASK"
    ansible.builtin.debug :
      msg : "Hello from {{ GREET }}"



  # 1) Command line or Args
  # 2) Task
  # 3) Files
  # 4) prompt
  # 5) PLAY
  # 6) Inventory

