- name : Install nginx  
  hosts : web
  become : yes
  tasks :
  - name : install ngix if RHEL
    ansible.builtin.dnf:
      name : nginx
      state : installed
    when: anisble_os_family == 'RedHat'
  - name : install ngix if Ubuntu
    ansible.builtin.apt:
      name : nginx
      state : installed
    when: anisble_os_family == 'Debian'

