- name : filters
  hosts : local
  connection : local
  tasks :
  - name : task1-Handling undefined variables
    ansible.builtin.debug:
      msg : "Hello {{ PERSON | default('Krishna') }}"
  
  - name : task2 - convert string to list
    vars:
      FRUITS : "Apple, Banana, Grapes, Orange"
    ansible.builtin.debug:
      msg : "Fruits are : {{ FRUITS | ansible.builtin.split(',') }}"
    
  - name : task3 - convert map/dictonary into list
    vars :
      COURSE :
        COURSE_NAME : DevOps
        DURATION : 120HRS
        SPEAKER : Sivakumar
    ansible.builtin.debug:
      msg : "Course details in list format : {{ COURSE | dict2items }}"
  
  - name : task4 - convert list to map/dictonary
    vars :
      COURSE :
      - {'key': 'COURSE_NAME', 'value': 'DevOps'}
      - {'key': 'DURATION', 'value': '120HRS'}
      - {'key': 'SPEAKER', 'value': 'Sivakumar'}
    ansible.builtin.debug:
      msg : "Course details in dictonary format : {{ COURSE | items2dict }}"

  - name : task5 - Convert upper to lower
    vars :
      NAME : 'Vishnu Priya Varada'
    ansible.builtin.debug:
      msg : " Name in lower format : {{ NAME | lower }} "

  - name : task6 - Convert lower to upper
    vars :
      NAME : 'Vishnu Priya Varada'
    ansible.builtin.debug:
      msg : " Name in lower format : {{ NAME | upper }} "

  - name : task7 - print min and max number
    vars :
      NUMBERS : [23,89, 14, 3, 1978, 4567]
    ansible.builtin.debug:
      msg : " Minimum number is : {{ NUMBERS | min }} and Maximum number is : {{ NUMBERS | max }} "

  - name : task8 - Check IP address is valid or not
    vars :
      IP_ADDRESS : 215.10.0.0
    ansible.builtin.debug:
      msg : " Is IP address is valid ? {{ IP_ADDRESS | ansible.utils.ipaddr }}"
