- name : filters
  hosts : local
  connection : local
  tasks :
  - name : task1-Handling undefined variables
    ansible.builtin.debug:
      msg : "Hello {{ PERSON | default('Krishna') }}"
  
  - name : task2 - convert string to list
    vars:
      FRUITS : "Apple, Banana, Grapes, Orange"
    ansible.builtin.debug:
      msg : "Fruits are : {{ FRUITS | ansible.builtin.split(',') }}"
    
  - name : task3 - convert map/dictonary into list
    vars :
      COURSE :
        COURSE_NAME : DevOps
        DURATION : 120HRS
        SPEAKER : Sivakumar
    ansible.builtin.debug
      msg : "Course details in list format : {{ COURSE | dict2items }}"
