- name : filters
  hosts : local
  connection : local
  tasks :
  - name : task1-Handling undefined variables
    ansible.builtin.debug:
      msg : "Hello {{ PERSON | default('Krishna') }}"
  
  - name : task2 - convert string to list
    vars:
      FRUITS : "Apple, Banana, Grapes, Orange"
    ansible.builtin.split:
      msg : "Fruits are : {{ FRUITS | split(',') }}"
    
    